# Generated by Django 4.0.1 on 2022-01-11 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id_shipment', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='sneakers',
            options={'verbose_name_plural': 'Sneakers'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Types'},
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='id_client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='id_sneakers',
            new_name='sneakers',
        ),
        migrations.RenameField(
            model_name='sneakers',
            old_name='id_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='sneakerstore.shipment'),
        ),
    ]
