# Generated by Django 4.0.1 on 2022-01-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakerstore', '0003_alter_orders_shipment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
